// <auto-generated />
using System;
using ChurchRegister.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurchRegister.Database.Migrations
{
    [DbContext(typeof(ChurchRegisterWebContext))]
    [Migration("20260220165908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChurchRegister.Database.Data.ChurchRegisterWebUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLineOne")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLineTwo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Town")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("BankReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Baptised")
                        .HasColumnType("bit");

                    b.Property<int?>("ChurchMemberStatusId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DataProtectionId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("GiftAid")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PastoralCareRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BankReference")
                        .IsUnique()
                        .HasDatabaseName("IX_ChurchMembers_BankReference_Unique")
                        .HasFilter("[BankReference] IS NOT NULL");

                    b.HasIndex("ChurchMemberStatusId");

                    b.HasIndex("DataProtectionId")
                        .IsUnique()
                        .HasFilter("[DataProtectionId] IS NOT NULL");

                    b.HasIndex("DistrictId");

                    b.ToTable("ChurchMembers");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberContributions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChurchMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ContributionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EnvelopeContributionBatchId")
                        .HasColumnType("int");

                    b.Property<int?>("HSBCBankCreditTransactionId")
                        .HasColumnType("int");

                    b.Property<bool>("ManualContribution")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchMemberId")
                        .HasDatabaseName("IX_ChurchMemberContributions_ChurchMemberId");

                    b.HasIndex("ContributionTypeId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_ChurchMemberContributions_Date");

                    b.HasIndex("EnvelopeContributionBatchId");

                    b.HasIndex("HSBCBankCreditTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChurchMemberContributions_HSBCTransactionId_Unique")
                        .HasFilter("[HSBCBankCreditTransactionId] IS NOT NULL");

                    b.ToTable("ChurchMemberContributions", t =>
                        {
                            t.HasCheckConstraint("CK_ChurchMemberContributions_Amount", "Amount >= 0");
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberDataProtection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowHealthStatusInCommunications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowNameInCommunications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowPhotoInCommunications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowPhotoInSocialMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ChurchMemberId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GroupPhotos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PermissionForMyChildren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ChurchMemberId")
                        .IsUnique();

                    b.ToTable("ChurchMemberDataProtection");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberRegisterNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchMemberId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchMemberId")
                        .HasDatabaseName("IX_ChurchMemberRegisterNumbers_ChurchMemberId");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_ChurchMemberRegisterNumbers_Year");

                    b.HasIndex("Year", "Number")
                        .HasDatabaseName("IX_ChurchMemberRegisterNumbers_Year_Number");

                    b.ToTable("ChurchMemberRegisterNumbers");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberRoleTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChurchMemberRoleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Non-Member"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Member"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deacon"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Auditor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Secretary"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Treasurer"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Minister"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Junior Church Leader"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "District Officer"
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ChurchMemberRoleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChurchMemberId");

                    b.HasIndex("ChurchMemberRoleTypeId");

                    b.ToTable("ChurchMemberRoles");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChurchMemberStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Expired"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "In Glory"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "InActive"
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberTrainingCertificates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchMemberId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrainingCertificateTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchMemberId");

                    b.HasIndex("TrainingCertificateTypeId");

                    b.ToTable("ChurchMemberTrainingCertificates");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ContributionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ContributionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Transfer"
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Districts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeaconId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DeaconId")
                        .HasDatabaseName("IX_Districts_DeaconId");

                    b.HasIndex("DistrictOfficerId")
                        .HasDatabaseName("IX_Districts_DistrictOfficerId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "D"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "E"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "F"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "G"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "H"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "I"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "J"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "K"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "L"
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.EnvelopeContributionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BatchDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnvelopeCount")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Submitted");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchDate")
                        .IsUnique()
                        .HasDatabaseName("IX_EnvelopeContributionBatch_BatchDate_Unique");

                    b.ToTable("EnvelopeContributionBatches", t =>
                        {
                            t.HasCheckConstraint("CK_EnvelopeContributionBatch_EnvelopeCount", "EnvelopeCount > 0");

                            t.HasCheckConstraint("CK_EnvelopeContributionBatch_TotalAmount", "TotalAmount >= 0");
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.EventAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attendance")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_EventAttendance_EventId_Date");

                    b.ToTable("EventAttendances");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowInAnalysis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 0,
                            Description = "Online streaming of Sunday morning service",
                            IsActive = true,
                            Name = "Sunday Morning Online",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 0,
                            Description = "Weekly Sunday morning worship service",
                            IsActive = true,
                            Name = "Sunday Morning Service",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 0,
                            Description = "Children's service during main worship",
                            IsActive = true,
                            Name = "Junior Church",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 0,
                            Description = "Sunday fellowship gathering",
                            IsActive = true,
                            Name = "Coffee Corner",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 0,
                            Description = "Weekly Sunday evening worship service",
                            IsActive = true,
                            Name = "Sunday Evening Service",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 0,
                            Description = "Evening prayer call service",
                            IsActive = true,
                            Name = "Sunday Evening Call",
                            ShowInAnalysis = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            Description = "Midweek inspirational service",
                            IsActive = true,
                            Name = "Just A Thought",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            Description = "Monthly men's fellowship meeting",
                            IsActive = true,
                            Name = "Men's Fellowship",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 2,
                            Description = "Tuesday morning prayer and worship",
                            IsActive = true,
                            Name = "Tuesday Morning Service",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 2,
                            Description = "Midweek Bible study and prayer meeting",
                            IsActive = true,
                            Name = "Bible Study",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            Description = "Open door community service",
                            IsActive = true,
                            Name = "Open Door",
                            ShowInAnalysis = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            Description = "Community outreach and meal service",
                            IsActive = true,
                            Name = "Soup Station",
                            ShowInAnalysis = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 4,
                            Description = "Choir rehearsal and practice",
                            IsActive = true,
                            Name = "Choir",
                            ShowInAnalysis = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 5,
                            Description = "Weekly youth fellowship and activities",
                            IsActive = true,
                            Name = "Youth Meeting",
                            ShowInAnalysis = true
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 6,
                            Description = "Saturday evening service",
                            IsActive = true,
                            Name = "Torch",
                            ShowInAnalysis = true
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.HSBCBankCreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MoneyIn")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_HSBCBankCreditTransactions_IsProcessed");

                    b.HasIndex("Reference")
                        .HasDatabaseName("IX_HSBCBankCreditTransactions_Reference");

                    b.ToTable("HSBCBankCreditTransactions");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Priority")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("IX_Reminders_AssignedToUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Reminders_DueDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Reminders_Status");

                    b.HasIndex("Status", "DueDate")
                        .HasDatabaseName("IX_Reminders_Status_DueDate");

                    b.ToTable("Reminders", t =>
                        {
                            t.HasCheckConstraint("CK_Reminders_Status", "[Status] IN ('Pending', 'Completed')");
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ReminderCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemCategory")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ReminderCategories_Name_Unique");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_ReminderCategories_SortOrder");

                    b.ToTable("ReminderCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#9e9e9e",
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemCategory = true,
                            Name = "None",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#f44336",
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemCategory = true,
                            Name = "Health & Safety",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#4caf50",
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemCategory = true,
                            Name = "Financial",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#ff9800",
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemCategory = true,
                            Name = "Risk Assessments",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#2196f3",
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemCategory = true,
                            Name = "Technical",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewInterval")
                        .HasColumnType("int");

                    b.Property<int?>("RiskAssessmentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_RiskAssessments_CategoryId");

                    b.HasIndex("NextReviewDate")
                        .HasDatabaseName("IX_RiskAssessments_NextReviewDate");

                    b.HasIndex("RiskAssessmentCategoryId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RiskAssessments_Status");

                    b.HasIndex("Status", "NextReviewDate")
                        .HasDatabaseName("IX_RiskAssessments_Status_NextReviewDate");

                    b.ToTable("RiskAssessments", t =>
                        {
                            t.HasCheckConstraint("CK_RiskAssessments_ReviewInterval", "[ReviewInterval] IN (1, 2, 3, 5)");

                            t.HasCheckConstraint("CK_RiskAssessments_Status", "[Status] IN ('Under Review', 'Approved')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive safeguarding controls",
                            NextReviewDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 1,
                            Status = "Approved",
                            Title = "Safeguarding Risk Assessment"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 2,
                            Status = "Approved",
                            Title = "Community Outreach & Services Risk Assessment"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 1,
                            Status = "Approved",
                            Title = "Health & Safety - General Risk Assessment"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 1,
                            Status = "Under Review",
                            Title = "Emergency Procedures Risk Assessment"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 3,
                            Status = "Under Review",
                            Title = "Financial Compliance Risk Assessment"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 2,
                            Status = "Under Review",
                            Title = "Data & Information Governance Risk Assessment"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 5,
                            Status = "Under Review",
                            Title = "Governance & Administration Risk Assessment"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextReviewDate = new DateTime(2026, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewInterval = 3,
                            Status = "Under Review",
                            Title = "Employment & HR Risk Assessment"
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessmentApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedByChurchMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RiskAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByChurchMemberId");

                    b.HasIndex("RiskAssessmentId", "ApprovedByChurchMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_RiskAssessmentApprovals_RiskAssessmentId_ApprovedByChurchMemberId_Unique");

                    b.ToTable("RiskAssessmentApprovals");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_RiskAssessmentCategories_Name_Unique");

                    b.ToTable("RiskAssessmentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Working with Children, Adults at Risk, Volunteers, DBS, Respect for Others",
                            Name = "Safeguarding"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soup Station protocols, entry/behavioral policies, food safety",
                            Name = "Community Outreach & Services"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perimeter, lone working, slips/trips/falls, working at height, personal safety, hazardous items, baptistry, general H&S",
                            Name = "Health & Safety - General"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fire safety/alarms, evacuation, first aid/accident reporting, terrorist attack",
                            Name = "Emergency Procedures"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Financial regulations, banking, finance risk, examiners, conflict of interest",
                            Name = "Financial Compliance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Data protection, retention & archive",
                            Name = "Data & Information Governance"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trustees, officers, safe environment, CCTV, music licence, digital/social media",
                            Name = "Governance & Administration"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grievance, disciplinary, capability, complaints",
                            Name = "Employment & HR"
                        });
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.TrainingCertificateTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingCertificateTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Type = "DBS"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Type = "Safeguarding Level 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Type = "Safeguarding Level 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Type = "Food Hygiene"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Type = "First Aid"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "system",
                            CreatedDateTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Type = "Fire Marshal"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMember", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.Address", "Address")
                        .WithMany("ChurchMembers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChurchRegister.Database.Entities.ChurchMemberStatus", "ChurchMemberStatus")
                        .WithMany("ChurchMembers")
                        .HasForeignKey("ChurchMemberStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChurchRegister.Database.Entities.ChurchMemberDataProtection", "DataProtection")
                        .WithOne()
                        .HasForeignKey("ChurchRegister.Database.Entities.ChurchMember", "DataProtectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChurchRegister.Database.Entities.Districts", "District")
                        .WithMany("ChurchMembers")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("ChurchMemberStatus");

                    b.Navigation("DataProtection");

                    b.Navigation("District");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberContributions", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "ChurchMember")
                        .WithMany("Contributions")
                        .HasForeignKey("ChurchMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Entities.ContributionType", "ContributionType")
                        .WithMany("ChurchMemberContributions")
                        .HasForeignKey("ContributionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Entities.EnvelopeContributionBatch", "EnvelopeContributionBatch")
                        .WithMany("ChurchMemberContributions")
                        .HasForeignKey("EnvelopeContributionBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchRegister.Database.Entities.HSBCBankCreditTransaction", "HSBCBankCreditTransaction")
                        .WithMany("Contributions")
                        .HasForeignKey("HSBCBankCreditTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChurchMember");

                    b.Navigation("ContributionType");

                    b.Navigation("EnvelopeContributionBatch");

                    b.Navigation("HSBCBankCreditTransaction");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberDataProtection", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", null)
                        .WithOne()
                        .HasForeignKey("ChurchRegister.Database.Entities.ChurchMemberDataProtection", "ChurchMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberRegisterNumber", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "ChurchMember")
                        .WithMany("RegisterNumbers")
                        .HasForeignKey("ChurchMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChurchMember");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberRoles", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "ChurchMember")
                        .WithMany("Roles")
                        .HasForeignKey("ChurchMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Entities.ChurchMemberRoleTypes", "ChurchMemberRoleType")
                        .WithMany("ChurchMemberRoles")
                        .HasForeignKey("ChurchMemberRoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChurchMember");

                    b.Navigation("ChurchMemberRoleType");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberTrainingCertificates", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "ChurchMember")
                        .WithMany("TrainingCertificates")
                        .HasForeignKey("ChurchMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Entities.TrainingCertificateTypes", "TrainingCertificateType")
                        .WithMany("ChurchMemberTrainingCertificates")
                        .HasForeignKey("TrainingCertificateTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChurchMember");

                    b.Navigation("TrainingCertificateType");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Districts", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "Deacon")
                        .WithMany()
                        .HasForeignKey("DeaconId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "DistrictOfficer")
                        .WithMany()
                        .HasForeignKey("DistrictOfficerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Deacon");

                    b.Navigation("DistrictOfficer");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.EventAttendance", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.Events", "Event")
                        .WithMany("EventAttendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Reminder", b =>
                {
                    b.HasOne("ChurchRegister.Database.Data.ChurchRegisterWebUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChurchRegister.Database.Entities.ReminderCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessment", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.RiskAssessmentCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Entities.RiskAssessmentCategory", null)
                        .WithMany("RiskAssessments")
                        .HasForeignKey("RiskAssessmentCategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessmentApproval", b =>
                {
                    b.HasOne("ChurchRegister.Database.Entities.ChurchMember", "ApprovedByChurchMember")
                        .WithMany()
                        .HasForeignKey("ApprovedByChurchMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany("Approvals")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByChurchMember");

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ChurchRegister.Database.Data.ChurchRegisterWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ChurchRegister.Database.Data.ChurchRegisterWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurchRegister.Database.Data.ChurchRegisterWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ChurchRegister.Database.Data.ChurchRegisterWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Address", b =>
                {
                    b.Navigation("ChurchMembers");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMember", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("RegisterNumbers");

                    b.Navigation("Roles");

                    b.Navigation("TrainingCertificates");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberRoleTypes", b =>
                {
                    b.Navigation("ChurchMemberRoles");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ChurchMemberStatus", b =>
                {
                    b.Navigation("ChurchMembers");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.ContributionType", b =>
                {
                    b.Navigation("ChurchMemberContributions");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Districts", b =>
                {
                    b.Navigation("ChurchMembers");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.EnvelopeContributionBatch", b =>
                {
                    b.Navigation("ChurchMemberContributions");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.Events", b =>
                {
                    b.Navigation("EventAttendances");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.HSBCBankCreditTransaction", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessment", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.RiskAssessmentCategory", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("ChurchRegister.Database.Entities.TrainingCertificateTypes", b =>
                {
                    b.Navigation("ChurchMemberTrainingCertificates");
                });
#pragma warning restore 612, 618
        }
    }
}
