import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
  Typography,
  Alert,
  CircularProgress,
  IconButton,
} from '@mui/material';
import {
  Close as CloseIcon,
  Download as DownloadIcon,
  Numbers as NumbersIcon,
} from '@mui/icons-material';
import { RegisterNumberPreviewGrid } from './RegisterNumberPreviewGrid';
import { ConfirmationModal } from './ConfirmationModal';
import { useRegisterNumbers } from '../../hooks/useRegisterNumbers';
import { exportRegisterNumbersToCSV } from '../../utils/exportUtils';
import { useNotification } from '../../hooks/useNotification';

export interface RegisterNumberGenerationDialogProps {
  open: boolean;
  onClose: () => void;
}

export const RegisterNumberGenerationDialog: React.FC<
  RegisterNumberGenerationDialogProps
> = ({ open, onClose }) => {
  const currentYear = new Date().getFullYear();
  const targetYear = currentYear + 1;

  const { showSuccess } = useNotification();
  const { preview, status, generate } = useRegisterNumbers(targetYear);

  const [showPreview, setShowPreview] = useState(false);
  const [showConfirmation, setShowConfirmation] = useState(false);

  // Load preview and status when dialog opens
  useEffect(() => {
    if (open) {
      setShowPreview(false);
      status.refetch();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Load preview after status check
  useEffect(() => {
    if (open && status.data) {
      if (!status.data.isGenerated) {
        // Not generated yet - show preview for generation
        preview.refetch().then(() => setShowPreview(true));
      } else {
        // Already generated - fetch to show what was generated
        preview.refetch();
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, status.data]);

  const handleGenerateClick = () => {
    setShowConfirmation(true);
  };

  const handleConfirmGeneration = async () => {
    try {
      await generate.mutateAsync({
        targetYear,
        confirmGeneration: true,
      });

      setShowConfirmation(false);

      // Refresh status and preview
      await status.refetch();
      if (status.data?.isGenerated) {
        await preview.refetch();
      }
    } catch (error) {
      console.error('Generation error:', error);
    }
  };

  const handleExport = () => {
    if (preview.data?.assignments) {
      exportRegisterNumbersToCSV(preview.data.assignments, targetYear);
      showSuccess(
        `Exported ${preview.data.assignments.length} register numbers to CSV`
      );
    }
  };

  const handleClose = () => {
    if (!generate.isPending) {
      setShowPreview(false);
      setShowConfirmation(false);
      onClose();
    }
  };

  const isLoading = status.isLoading || preview.isLoading;
  const isGenerated = status.data?.isGenerated || false;

  return (
    <>
      <Dialog
        open={open}
        onClose={handleClose}
        maxWidth="lg"
        fullWidth
        PaperProps={{
          sx: { height: '90vh' },
        }}
      >
        <DialogTitle>
          <Box
            display="flex"
            alignItems="center"
            justifyContent="space-between"
            sx={{
              bgcolor: 'grey.100',
              p: 2,
              m: -3,
              mb: 0,
              borderRadius: '4px 4px 0 0',
            }}
          >
            <Box display="flex" alignItems="center" gap={1}>
              <NumbersIcon sx={{ color: 'primary.main' }} />
              <Typography variant="h6" color="primary.main" fontWeight="bold">
                Generate Membership Numbers for {targetYear}
              </Typography>
            </Box>
            <IconButton
              edge="end"
              onClick={handleClose}
              aria-label="close"
              disabled={generate.isPending}
              sx={{ color: 'primary.main' }}
            >
              <CloseIcon />
            </IconButton>
          </Box>
        </DialogTitle>

        <DialogContent dividers>
          {isLoading && (
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              minHeight={300}
            >
              <CircularProgress />
            </Box>
          )}

          {!isLoading && isGenerated && (
            <Alert severity="info" sx={{ mb: 2 }}>
              Membership numbers for {targetYear} have already been generated by{' '}
              {status.data?.generatedBy} on{' '}
              {status.data?.generatedDateTime
                ? new Date(status.data.generatedDateTime).toLocaleString(
                    'en-GB'
                  )
                : 'an unknown date'}
              . Total assignments: {status.data?.totalAssignments || 0}.
            </Alert>
          )}

          {!isLoading && !isGenerated && !showPreview && (
            <Alert severity="warning">Preparing preview...</Alert>
          )}

          {!isLoading && !isGenerated && showPreview && preview.data && (
            <>
              <Alert severity="warning" sx={{ mb: 2 }}>
                <Typography variant="body2" fontWeight="bold" gutterBottom>
                  ⚠️ Important: This action is permanent and cannot be undone
                </Typography>
                <Typography variant="body2">
                  Membership numbers will be assigned to{' '}
                  {preview.data.totalActiveMembers} active members based on
                  their membership seniority. Please review the preview
                  carefully before generating.
                </Typography>
              </Alert>

              <RegisterNumberPreviewGrid
                assignments={preview.data.assignments}
                year={targetYear}
                currentYear={currentYear}
                loading={preview.isLoading}
              />
            </>
          )}

          {!isLoading && isGenerated && preview.data && (
            <RegisterNumberPreviewGrid
              assignments={preview.data.assignments}
              year={targetYear}
              currentYear={currentYear}
              loading={preview.isLoading}
            />
          )}
        </DialogContent>

        <DialogActions sx={{ p: 2, gap: 1 }}>
          <Button onClick={handleClose} disabled={generate.isPending}>
            Close
          </Button>

          {!isGenerated && showPreview && preview.data && (
            <Button
              onClick={handleGenerateClick}
              variant="contained"
              color="primary"
              disabled={
                generate.isPending || preview.data.totalActiveMembers === 0
              }
              startIcon={
                generate.isPending ? (
                  <CircularProgress size={20} />
                ) : (
                  <NumbersIcon />
                )
              }
            >
              {generate.isPending
                ? 'Generating...'
                : `Generate for ${targetYear}`}
            </Button>
          )}

          {(isGenerated ||
            (preview.data && preview.data.assignments.length > 0)) && (
            <Button
              onClick={handleExport}
              variant="outlined"
              startIcon={<DownloadIcon />}
              disabled={!preview.data}
            >
              Export to CSV
            </Button>
          )}
        </DialogActions>
      </Dialog>

      <ConfirmationModal
        open={showConfirmation}
        onClose={() => setShowConfirmation(false)}
        onConfirm={handleConfirmGeneration}
        title="Confirm Number Generation"
        message={`Are you sure you want to generate membership numbers for ${targetYear}? This action is permanent and will assign numbers to ${preview.data?.totalActiveMembers || 0} active members.`}
        confirmText="Generate Numbers"
        cancelText="Cancel"
        variant="warning"
        loading={generate.isPending}
      />
    </>
  );
};
